ARG CANN_IMAGE="quay.io/ascend/cann:9.0.1-a3-ubuntu22.04-py3.12"
ARG UV_IMAGE="ghcr.io/astral-sh/uv:0.11.30"
FROM ${UV_IMAGE} AS uv-bin

FROM ${CANN_IMAGE} AS ek-worker-ascend-runtime

COPY --from=uv-bin /uv /uvx /usr/local/bin/

ENV UV_PYTHON_DOWNLOADS=0
WORKDIR /opt/expert-kit

COPY pyproject.toml uv.lock ./
COPY ek-proto/pyproject.toml ./ek-proto/pyproject.toml
COPY ek-transport/pyproject.toml ./ek-transport/pyproject.toml
COPY ek-worker/pyproject.toml ./ek-worker/pyproject.toml
COPY ek-integration/expertkit_torch/pyproject.toml \
    ./ek-integration/expertkit_torch/pyproject.toml
COPY ek-integration/expertkit_vllm/pyproject.toml \
    ./ek-integration/expertkit_vllm/pyproject.toml

RUN --mount=type=cache,target=/root/.cache/uv \
    UV_LINK_MODE=copy \
    uv sync \
      --locked \
      --package expertkit-worker \
      --extra npu \
      --no-dev \
      --no-install-workspace

COPY ek-proto/ ./ek-proto/
COPY ek-transport/ ./ek-transport/
COPY ek-worker/ ./ek-worker/

RUN --mount=type=cache,target=/root/.cache/uv \
    UV_LINK_MODE=copy \
    uv sync \
      --locked \
      --package expertkit-worker \
      --extra npu \
      --no-dev

ARG VLLM_ASCEND_IMAGE="quay.io/ascend/vllm-ascend:v0.23.0rc1-a3"
FROM ${VLLM_ASCEND_IMAGE} as ek-vllm-ascend-runtime

WORKDIR /opt/expert-kit
COPY pyproject.toml uv.lock ./
COPY ek-proto/ ek-proto/
COPY ek-transport/ ek-transport/
COPY ek-worker/ ek-worker/
COPY ek-integration/expertkit_vllm/ ek-integration/expertkit_vllm
