[workspace]
resolver = "2"
members = [
    "ek-base",
    "ek-cli",
    "ek-computation",
    "ek-db",
]
default-members = ["ek-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Expert-Kit Team"]
license = "LGPL-3.0"
readme = "README.md"
repository = "https://github.com/expert-kit/expert-kit"

[workspace.dependencies]
# Internal dependencies
ek-base = { path = "ek-base" }
ek-computation = { path = "ek-computation" }
ek-db = { path = "ek-db" }

# External dependencies (alphabetical order)
actix-web = "4.10.2"
async-trait = "0.1.88"
bytes = "1.10.1"
clap = { version = "4.5.31", features = ["derive"] }
config = "0.15.11"
diesel = { version = "2.2.9", features = [
    "postgres",
    "serde_json",
    "r2d2",
    "uuid",
    "chrono",
] }
diesel-async = { version = "0.5.2", features = ["deadpool", "postgres"] }
diesel_migrations = "2.2.0"
env_logger = { version = "0.11.8", features = ["kv"] }
indicatif = "0.17.11"
log = { version = "0.4.26", features = ["kv"] }
memmap2 = "0.9.5"
opendal = { version = "0.52.0", features = ["services-s3", "services-fs"] }
opentelemetry = { version = "0.29.0", default-features = false, features = [
    "trace",
] }
opentelemetry_sdk = { version = "0.29.0", default-features = false, features = [
    "trace",
] }
opentelemetry-otlp = { version = "0.29.0", features = [
    "metrics",
    "grpc-tonic",
] }
opentelemetry-semantic-conventions = { version = "0.29.0", features = [
    "semconv_experimental",
] }
prost = "0.13"
protoc-bin-vendored = "3"
rand = "0.9.1"
reqwest = "0.12.15"
safetensors = "0.5.3"
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
thiserror = "2"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.17"
tonic = "0.13.1"
tonic-build = "0.13.1"
tracing = { version = "0.1.41", default-features = false, features = [
    "std",
    "attributes",
] }
tracing-opentelemetry = "0.30.0"
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
    "std",
    "registry",
    "local-time",
] }
url = "2.5.7"
