version: "3"
services:
  ek-postgres:
    container_name: ek-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5430:5432"
    volumes:
      - ../data/pg:/var/lib/postgresql/data
    networks:
      - expert-kit-network
  ek-migrations:
    build:
      context: ../
      dockerfile: ../docker/Dockerfile.cpu
      target: controller
    depends_on:
      ek-postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://dev:dev@ek-postgres:5432/dev
    volumes:
      - ../ek-computation/migrations:/app/ek-migrations
    working_dir: /app/ek-migrations
    command: diesel migration run --migration-dir /app/ek-migrations
    networks:
      - expert-kit-network
  ek-controller:
    build:
      context: ../
      dockerfile: ../docker/Dockerfile.cpu
      target: controller
    container_name: ek-controller
    restart: unless-stopped 
    depends_on:
      ek-postgres:
        condition: service_healthy
    ports:
      - 5001:5001
      - 5002:5002
    volumes:
      - ../dev:/app/dev
      - ../data:/app/data
      - ./config:/etc/expert-kit:ro
    environment:
      - RUST_LOG=info
    networks:
      - expert-kit-network
  ek-worker:
    build:
      context: ../
      dockerfile: ../docker/Dockerfile.cpu
      target: worker
    container_name: ek-worker
    restart: unless-stopped
    depends_on:
      - ek-controller
    volumes:
      - ../data:/app/data
      - ./config:/etc/expert-kit:ro
    environment:
      - EK_HOSTNAME=local-dev
      - EK_CONTROL_PLAN_ADDR=http://ek-controller:5001
      - RUST_LOG=info
      - LD_LIBRARY_PATH=/opt/torch/libtorch/lib:$LD_LIBRARY_PATH
    networks:
      - expert-kit-network

networks:
  expert-kit-network:
    driver: bridge