version: "3"
services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - ../data/pg:/var/lib/postgresql/data