from contextlib import AbstractContextManager
from typing import Protocol

import torch


class DeviceWork(Protocol):
    def wait_host(self) -> None: ...


class WorkerDeviceRuntime(Protocol):
    """Capabilities shared by synchronous and asynchronous devices."""

    device: torch.device

    def device_context(self) -> AbstractContextManager[None]: ...
    def memory_info(self) -> tuple[int, int]: ...
    def capture_current_work(self) -> DeviceWork: ...


class AsyncWorkerDeviceRuntime[StreamT, EventT](WorkerDeviceRuntime, Protocol):
    """Interface for worker device runtime"""

    device: torch.device

    def create_stream(self, *, priority: int = 0) -> StreamT: ...
    def current_stream(self) -> StreamT: ...
    def synchronize_stream(self, stream: StreamT) -> None: ...
    def stream_context(self, stream: StreamT) -> AbstractContextManager[None]: ...

    def create_event(self, *, enable_timing: bool = False) -> EventT: ...
    def record_event(self, event: EventT, stream: StreamT) -> None: ...
    def wait_event(self, stream: StreamT, event: EventT) -> None: ...
    def synchronize_event(self, event: EventT) -> None: ...
    def event_done(self, event: EventT) -> bool: ...

    def set_current_device(self) -> None: ...
    def synchronize_device(self) -> None: ...

    def elapsed_time_ms(self, start: EventT, end: EventT) -> float: ...
