# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from expertkit_proto.ek.worker.v2 import computation_pb2 as ek_dot_worker_dot_v2_dot_computation__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ek/worker/v2/computation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputationServiceStub(object):
    """ComputationService executes one physical Worker batch per unary call.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/ek.worker.v2.ComputationService/Execute',
                request_serializer=ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.OpenSharedMemory = channel.unary_unary(
                '/ek.worker.v2.ComputationService/OpenSharedMemory',
                request_serializer=ek_dot_worker_dot_v2_dot_computation__pb2.OpenSharedMemoryRequest.SerializeToString,
                response_deserializer=ek_dot_worker_dot_v2_dot_computation__pb2.OpenSharedMemoryResponse.FromString,
                _registered_method=True)
        self.ExecuteSharedMemory = channel.unary_unary(
                '/ek.worker.v2.ComputationService/ExecuteSharedMemory',
                request_serializer=ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteSharedMemoryRequest.SerializeToString,
                response_deserializer=ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteSharedMemoryResponse.FromString,
                _registered_method=True)
        self.CloseSharedMemory = channel.unary_unary(
                '/ek.worker.v2.ComputationService/CloseSharedMemory',
                request_serializer=ek_dot_worker_dot_v2_dot_computation__pb2.CloseSharedMemoryRequest.SerializeToString,
                response_deserializer=ek_dot_worker_dot_v2_dot_computation__pb2.CloseSharedMemoryResponse.FromString,
                _registered_method=True)


class ComputationServiceServicer(object):
    """ComputationService executes one physical Worker batch per unary call.
    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSharedMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSharedMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSharedMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteRequest.FromString,
                    response_serializer=ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteResponse.SerializeToString,
            ),
            'OpenSharedMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSharedMemory,
                    request_deserializer=ek_dot_worker_dot_v2_dot_computation__pb2.OpenSharedMemoryRequest.FromString,
                    response_serializer=ek_dot_worker_dot_v2_dot_computation__pb2.OpenSharedMemoryResponse.SerializeToString,
            ),
            'ExecuteSharedMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSharedMemory,
                    request_deserializer=ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteSharedMemoryRequest.FromString,
                    response_serializer=ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteSharedMemoryResponse.SerializeToString,
            ),
            'CloseSharedMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSharedMemory,
                    request_deserializer=ek_dot_worker_dot_v2_dot_computation__pb2.CloseSharedMemoryRequest.FromString,
                    response_serializer=ek_dot_worker_dot_v2_dot_computation__pb2.CloseSharedMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.worker.v2.ComputationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.worker.v2.ComputationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputationService(object):
    """ComputationService executes one physical Worker batch per unary call.
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.worker.v2.ComputationService/Execute',
            ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteRequest.SerializeToString,
            ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSharedMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.worker.v2.ComputationService/OpenSharedMemory',
            ek_dot_worker_dot_v2_dot_computation__pb2.OpenSharedMemoryRequest.SerializeToString,
            ek_dot_worker_dot_v2_dot_computation__pb2.OpenSharedMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSharedMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.worker.v2.ComputationService/ExecuteSharedMemory',
            ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteSharedMemoryRequest.SerializeToString,
            ek_dot_worker_dot_v2_dot_computation__pb2.ExecuteSharedMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSharedMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.worker.v2.ComputationService/CloseSharedMemory',
            ek_dot_worker_dot_v2_dot_computation__pb2.CloseSharedMemoryRequest.SerializeToString,
            ek_dot_worker_dot_v2_dot_computation__pb2.CloseSharedMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
