[package]
name = "ek_computation"
version = "0.1.0"
edition = "2024"

[dependencies]

serde = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
rmp-serde = { workspace = true }
tch = { workspace = true }
ndarray = { workspace = true }
ndarray-rand = { workspace = true }
ort = { workspace = true }
polars = { workspace = true }
polars-io = { workspace = true }
clap = { workspace = true }
pretty_env_logger = { workspace = true }
sysinfo = "0.33.1"
log = { workspace = true }
safetensors = { workspace = true }
ek_base = { path = "../ek-base" }
opendal = { workspace = true }
async-trait = "0.1.88"
bytes = "1.10.1"


[build-dependencies]
tonic-build = "*"

[[example]]
name = "simple_client"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]
