# This file contains default variables for the Ansible role to install LibTorch.
torch_version: "2.7.0"
# cu118,cu128,cu128
torch_platform: "cpu"
# Specify the architecture (e.g., 'linux', 'windows', 'macos').
torch_os: "cxx11-abi-shared-with-deps"
# https://download.pytorch.org/libtorch/cpu/libtorch-macos-arm64-2.7.0.zip

torch_base_url: "https://download.pytorch.org/libtorch"
torch_download_url: "{{ torch_base_url }}/{{ torch_platform }}/libtorch-{{ torch_os }}-{{ torch_version }}%2B{{ torch_platform }}.zip"

# Specify the destination path for the downloaded archive.
torch_download_dest: "/tmp/libtorch-{{ torch_version }}.zip"

# Specify the installation path for LibTorch.
torch_install_path: "/opt/"
