# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ek/control/v1/control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ek/control/v1/control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from expertkit_vllm.pbpy.ek.object.v1 import object_pb2 as ek_dot_object_dot_v1_dot_object__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65k/control/v1/control.proto\x12\rek.control.v1\x1a\x19\x65k/object/v1/object.proto\"9\n\rCreatePlanReq\x12(\n\x04plan\x18\x02 \x01(\x0b\x32\x1a.ek.object.v1.SchedulePlan\":\n\x0e\x43reatePlanResp\x12(\n\x04plan\x18\x02 \x01(\x0b\x32\x1a.ek.object.v1.SchedulePlan\" \n\rDeletePlanReq\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\"\x10\n\x0e\x44\x65letePlanResp\"\x10\n\x0eInspectPlanReq\";\n\x0fInspectPlanResp\x12(\n\x04plan\x18\x01 \x03(\x0b\x32\x1a.ek.object.v1.SchedulePlan\"3\n\x0eResolveRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08slice_id\x18\x02 \x01(\t\"1\n\x0cResolveReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08slice_id\x18\x02 \x01(\t2\xe5\x01\n\x0bPlanService\x12\x45\n\x06\x43reate\x12\x1c.ek.control.v1.CreatePlanReq\x1a\x1d.ek.control.v1.CreatePlanResp\x12\x45\n\x06\x44\x65lete\x12\x1c.ek.control.v1.DeletePlanReq\x1a\x1d.ek.control.v1.DeletePlanResp\x12H\n\x07Inspect\x12\x1d.ek.control.v1.InspectPlanReq\x1a\x1e.ek.control.v1.InspectPlanResp2Y\n\x10\x44iscoveryService\x12\x45\n\x07Resolve\x12\x1d.ek.control.v1.ResolveRequest\x1a\x1b.ek.control.v1.ResolveReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ek.control.v1.control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPLANREQ']._serialized_start=73
  _globals['_CREATEPLANREQ']._serialized_end=130
  _globals['_CREATEPLANRESP']._serialized_start=132
  _globals['_CREATEPLANRESP']._serialized_end=190
  _globals['_DELETEPLANREQ']._serialized_start=192
  _globals['_DELETEPLANREQ']._serialized_end=224
  _globals['_DELETEPLANRESP']._serialized_start=226
  _globals['_DELETEPLANRESP']._serialized_end=242
  _globals['_INSPECTPLANREQ']._serialized_start=244
  _globals['_INSPECTPLANREQ']._serialized_end=260
  _globals['_INSPECTPLANRESP']._serialized_start=262
  _globals['_INSPECTPLANRESP']._serialized_end=321
  _globals['_RESOLVEREQUEST']._serialized_start=323
  _globals['_RESOLVEREQUEST']._serialized_end=374
  _globals['_RESOLVEREPLY']._serialized_start=376
  _globals['_RESOLVEREPLY']._serialized_end=425
  _globals['_PLANSERVICE']._serialized_start=428
  _globals['_PLANSERVICE']._serialized_end=657
  _globals['_DISCOVERYSERVICE']._serialized_start=659
  _globals['_DISCOVERYSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
