# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from expertkit_proto.ek.control.v2 import lifecycle_pb2 as ek_dot_control_dot_v2_dot_lifecycle__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ek/control/v2/lifecycle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InstanceServiceStub(object):
    """InstanceService resolves the one model instance managed by this Controller.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveDefaultInstance = channel.unary_unary(
                '/ek.control.v2.InstanceService/ResolveDefaultInstance',
                request_serializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.ResolveDefaultInstanceRequest.SerializeToString,
                response_deserializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.ResolveDefaultInstanceResponse.FromString,
                _registered_method=True)


class InstanceServiceServicer(object):
    """InstanceService resolves the one model instance managed by this Controller.
    """

    def ResolveDefaultInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveDefaultInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveDefaultInstance,
                    request_deserializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.ResolveDefaultInstanceRequest.FromString,
                    response_serializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.ResolveDefaultInstanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.control.v2.InstanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.control.v2.InstanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InstanceService(object):
    """InstanceService resolves the one model instance managed by this Controller.
    """

    @staticmethod
    def ResolveDefaultInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v2.InstanceService/ResolveDefaultInstance',
            ek_dot_control_dot_v2_dot_lifecycle__pb2.ResolveDefaultInstanceRequest.SerializeToString,
            ek_dot_control_dot_v2_dot_lifecycle__pb2.ResolveDefaultInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerLifecycleServiceStub(object):
    """WorkerLifecycleService registers one process and receives its liveness stream.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/ek.control.v2.WorkerLifecycleService/RegisterWorker',
                request_serializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.stream_unary(
                '/ek.control.v2.WorkerLifecycleService/Heartbeat',
                request_serializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.HeartbeatSummary.FromString,
                _registered_method=True)


class WorkerLifecycleServiceServicer(object):
    """WorkerLifecycleService registers one process and receives its liveness stream.
    """

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerLifecycleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.stream_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.HeartbeatRequest.FromString,
                    response_serializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.HeartbeatSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.control.v2.WorkerLifecycleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.control.v2.WorkerLifecycleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerLifecycleService(object):
    """WorkerLifecycleService registers one process and receives its liveness stream.
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v2.WorkerLifecycleService/RegisterWorker',
            ek_dot_control_dot_v2_dot_lifecycle__pb2.RegisterWorkerRequest.SerializeToString,
            ek_dot_control_dot_v2_dot_lifecycle__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ek.control.v2.WorkerLifecycleService/Heartbeat',
            ek_dot_control_dot_v2_dot_lifecycle__pb2.HeartbeatRequest.SerializeToString,
            ek_dot_control_dot_v2_dot_lifecycle__pb2.HeartbeatSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TopologyServiceStub(object):
    """TopologyService streams a contiguous update history or a complete snapshot.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchTopology = channel.unary_stream(
                '/ek.control.v2.TopologyService/WatchTopology',
                request_serializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.WatchTopologyRequest.SerializeToString,
                response_deserializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.TopologyMessage.FromString,
                _registered_method=True)


class TopologyServiceServicer(object):
    """TopologyService streams a contiguous update history or a complete snapshot.
    """

    def WatchTopology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopologyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchTopology': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTopology,
                    request_deserializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.WatchTopologyRequest.FromString,
                    response_serializer=ek_dot_control_dot_v2_dot_lifecycle__pb2.TopologyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.control.v2.TopologyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.control.v2.TopologyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TopologyService(object):
    """TopologyService streams a contiguous update history or a complete snapshot.
    """

    @staticmethod
    def WatchTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ek.control.v2.TopologyService/WatchTopology',
            ek_dot_control_dot_v2_dot_lifecycle__pb2.WatchTopologyRequest.SerializeToString,
            ek_dot_control_dot_v2_dot_lifecycle__pb2.TopologyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
