# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from expertkit_proto.ek.control.v2 import weight_control_pb2 as ek_dot_control_dot_v2_dot_weight__control__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ek/control/v2/weight_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeightControlServiceStub(object):
    """WeightControlService carries desired placement and observed expert state.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sync = channel.stream_stream(
                '/ek.control.v2.WeightControlService/Sync',
                request_serializer=ek_dot_control_dot_v2_dot_weight__control__pb2.WorkerWeightMessage.SerializeToString,
                response_deserializer=ek_dot_control_dot_v2_dot_weight__control__pb2.ControllerWeightMessage.FromString,
                _registered_method=True)


class WeightControlServiceServicer(object):
    """WeightControlService carries desired placement and observed expert state.
    """

    def Sync(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeightControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sync': grpc.stream_stream_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=ek_dot_control_dot_v2_dot_weight__control__pb2.WorkerWeightMessage.FromString,
                    response_serializer=ek_dot_control_dot_v2_dot_weight__control__pb2.ControllerWeightMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.control.v2.WeightControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.control.v2.WeightControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeightControlService(object):
    """WeightControlService carries desired placement and observed expert state.
    """

    @staticmethod
    def Sync(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ek.control.v2.WeightControlService/Sync',
            ek_dot_control_dot_v2_dot_weight__control__pb2.WorkerWeightMessage.SerializeToString,
            ek_dot_control_dot_v2_dot_weight__control__pb2.ControllerWeightMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
