from __future__ import annotations

import shutil
from pathlib import Path
from typing import Annotated

import typer

from renderer import Renderer
from schemas.cluster import ClusterConfig
from schemas.context import TemplateContext
from schemas.experiment import ExperimentConfig
from generate import (
    TEMPLATE_DIR,
    DEFAULT_CLUSTER_CONFIG,
    DEFAULT_EXPERIMENT_CONFIG,
    DEFAULT_OUTPUT_DIR,
    generate_root_config,
    generate_pools_config,
)


app = typer.Typer(
    help="Validate and render Ascend deployment configuration.",
    no_args_is_help=True,
    pretty_exceptions_show_locals=False,
)

GENERATED_MARKER = ".expert-kit-generated"


def prepare_output_directory(output: Path) -> None:
    if output.exists():
        if not output.is_dir():
            raise typer.BadParameter(f"output is not a directory: {output}")

        is_default_output = output.resolve() == DEFAULT_OUTPUT_DIR.resolve()
        is_empty = not any(output.iterdir())
        is_generated = (output / GENERATED_MARKER).is_file()
        if not (is_default_output or is_empty or is_generated):
            raise typer.BadParameter(
                f"refusing to remove unmarked output directory: {output}"
            )
        shutil.rmtree(output)

    output.mkdir(exist_ok=True, parents=True)
    (output / GENERATED_MARKER).write_text(
        "Generated by dev/ascend/cli.py. Do not edit.\n",
        encoding="utf-8",
    )


@app.callback()
def main() -> None:
    """Validate and render Ascend deployment configuration."""


@app.command()
def generate(
    cluster: Annotated[
        Path,
        typer.Option(
            exists=True,
            dir_okay=False,
            readable=True,
            help="Cluster YAML.",
        ),
    ] = DEFAULT_CLUSTER_CONFIG,
    experiment: Annotated[
        Path,
        typer.Option(
            exists=True,
            dir_okay=False,
            readable=True,
            help="Experiment YAML.",
        ),
    ] = DEFAULT_EXPERIMENT_CONFIG,
    output: Annotated[
        Path,
        typer.Option(
            file_okay=False,
            help="Generated output directory.",
        ),
    ] = DEFAULT_OUTPUT_DIR,
) -> None:
    """Generate role-specific Compose and runtime YAML."""
    cluster_config = ClusterConfig.from_yaml(cluster)
    experiment_config = ExperimentConfig.from_yaml(experiment)
    context = TemplateContext.from_config(cluster_config, experiment_config)

    renderer = Renderer(TEMPLATE_DIR)
    prepare_output_directory(output)
    generate_root_config(renderer, context, output)
    generate_pools_config(renderer, context, output)


if __name__ == "__main__":
    app()
