inference:
  instance_name: local-test
  model_name: ds-tiny
  hidden_dim: 16
  intermediate_dim: 8
  
db:
  db_dsn: postgres://dev:dev@localhost:5432/dev
  max_conn_size: 32

weight:
  server:
    addr: http://ek-weight-server:6543
  cache:
    Fs:
      path: /tmp/expert-kit/cache

worker:
  id: local-dev
  listen: 0.0.0.0
  broadcast: ek-worker
  ports:
    main: 51234

controller:
  listen: 0.0.0.0
  broadcast: ek-controller
  ports:
    intra: 5001
    inter: 5002
