# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: expert.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'expert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65xpert.proto\x12\x02\x65k\"V\n\x14\x45xpertForwardRequest\x12\r\n\x05layer\x18\x01 \x01(\x05\x12\x0b\n\x03idx\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x0e\n\x06tensor\x18\x04 \x01(\x0c\"+\n\x12\x45xpertForwardReply\x12\x15\n\routput_tensor\x18\x01 \x01(\x0c\x32P\n\x11\x45xpertComputation\x12;\n\x07\x46orward\x12\x18.ek.ExpertForwardRequest\x1a\x16.ek.ExpertForwardReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'expert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPERTFORWARDREQUEST']._serialized_start=20
  _globals['_EXPERTFORWARDREQUEST']._serialized_end=106
  _globals['_EXPERTFORWARDREPLY']._serialized_start=108
  _globals['_EXPERTFORWARDREPLY']._serialized_end=151
  _globals['_EXPERTCOMPUTATION']._serialized_start=153
  _globals['_EXPERTCOMPUTATION']._serialized_end=233
# @@protoc_insertion_point(module_scope)
