# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from expertkit_torch.pbpy.ek.control.v1 import control_pb2 as ek_dot_control_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ek/control/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/ek.control.v1.PlanService/Create',
                request_serializer=ek_dot_control_dot_v1_dot_control__pb2.CreatePlanReq.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_control__pb2.CreatePlanResp.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/ek.control.v1.PlanService/Delete',
                request_serializer=ek_dot_control_dot_v1_dot_control__pb2.DeletePlanReq.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_control__pb2.DeletePlanResp.FromString,
                _registered_method=True)
        self.Inspect = channel.unary_unary(
                '/ek.control.v1.PlanService/Inspect',
                request_serializer=ek_dot_control_dot_v1_dot_control__pb2.InspectPlanReq.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_control__pb2.InspectPlanResp.FromString,
                _registered_method=True)


class PlanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=ek_dot_control_dot_v1_dot_control__pb2.CreatePlanReq.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_control__pb2.CreatePlanResp.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=ek_dot_control_dot_v1_dot_control__pb2.DeletePlanReq.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_control__pb2.DeletePlanResp.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=ek_dot_control_dot_v1_dot_control__pb2.InspectPlanReq.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_control__pb2.InspectPlanResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.control.v1.PlanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.control.v1.PlanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v1.PlanService/Create',
            ek_dot_control_dot_v1_dot_control__pb2.CreatePlanReq.SerializeToString,
            ek_dot_control_dot_v1_dot_control__pb2.CreatePlanResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v1.PlanService/Delete',
            ek_dot_control_dot_v1_dot_control__pb2.DeletePlanReq.SerializeToString,
            ek_dot_control_dot_v1_dot_control__pb2.DeletePlanResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v1.PlanService/Inspect',
            ek_dot_control_dot_v1_dot_control__pb2.InspectPlanReq.SerializeToString,
            ek_dot_control_dot_v1_dot_control__pb2.InspectPlanResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Resolve = channel.unary_unary(
                '/ek.control.v1.DiscoveryService/Resolve',
                request_serializer=ek_dot_control_dot_v1_dot_control__pb2.ResolveRequest.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_control__pb2.ResolveReply.FromString,
                _registered_method=True)


class DiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Resolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=ek_dot_control_dot_v1_dot_control__pb2.ResolveRequest.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_control__pb2.ResolveReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.control.v1.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.control.v1.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v1.DiscoveryService/Resolve',
            ek_dot_control_dot_v1_dot_control__pb2.ResolveRequest.SerializeToString,
            ek_dot_control_dot_v1_dot_control__pb2.ResolveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
