- name: Check if LibTorch is already installed
  ansible.builtin.find:
    name: "{{ torch_install_path }}/libtorch"
    patterns: "build-version"
    contains: "{{ torch_version }}"
    file_type: file
  register: libtorch_installed_check

- name: Ensure the installation directory exists
  ansible.builtin.file:
    path: "{{ torch_install_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  when: libtorch_installed_check.matched== 0

- name: Download LibTorch archive
  ansible.builtin.get_url:
    url: "{{ torch_download_url }}"
    dest: "{{ torch_download_dest }}"
    mode: "0644"
    checksum: "" # You might want to add a checksum for verification
    timeout: 600 # Increase timeout for large downloads
  when: libtorch_installed_check.matched== 0

- name: Unarchive LibTorch
  ansible.builtin.unarchive:
    src: "{{ torch_download_dest }}"
    dest: "{{ torch_install_path }}"
    remote_src: true
  when: libtorch_installed_check.matched== 0
